services:
  # Banco MySQL
  db:
    image: mysql:8.0
    container_name: ankaflow_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ankaflow_db
      MYSQL_USER: anka_user
      MYSQL_PASSWORD: anka123
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - ankaflow_mysql_data:/var/lib/mysql
    networks:
      - anka_network
    command: >
      --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Backend AnkaFlow
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ankaflow_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://root:root123@db:3306/ankaflow_db"
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - anka_network
    command: >
      sh -c "
        echo 'Aguardando banco de dados...' &&
        sleep 15 &&
        echo 'Gerando cliente Prisma...' &&
        npx prisma generate &&
        echo 'Criando tabelas...' &&
        npx prisma db push --accept-data-loss &&
        echo 'Iniciando servidor...' &&
        npm start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend AnkaFlow
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ankaflow_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      NEXT_PUBLIC_APP_NAME: "AnkaFlow"
      NEXT_PUBLIC_APP_VERSION: "1.0.0"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - anka_network

volumes:
  ankaflow_mysql_data:
    driver: local

networks:
  anka_network:
    driver: bridge